modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"

[[mods]]
modId="power"
version="1.2.0-dev32"
displayName="Keepers of the Stones"
credits="Created by MagicalAlexey"
displayURL="https://www.curseforge.com/minecraft/mc-mods/keepers-of-the-stones"
updateJSONURL="https://raw.githubusercontent.com/MagicalAlexey/Keepers-of-the-Stones/main/kosdev.json"
logoFile="logo.png"
authors="MagicalAlexey, ChiffonMedal"
description='''
This mod will add new sources of energy to the world with which you can transform into masters of the elements.
'''

[[dependencies.power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




